# Generated by Django 6.0.3 on 2026-03-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_bodymetrics_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymetrics',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
