# Generated by Django 6.0.3 on 2026-03-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_bodymetrics_weight_kg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodymetrics',
            options={'ordering': ['-created_at'], 'verbose_name': 'body metric', 'verbose_name_plural': 'body metrics'},
        ),
        migrations.RenameField(
            model_name='bodymetrics',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='bodymetrics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
