class BodyMetricStates:
    WAITING_VALUE = 1


class WorkoutStates:
    ENTER_SET_WEIGHT = 100
    ENTER_SET_REPS = 101
    CREATE_EXERCISE_NAME = 102
    CREATE_EXERCISE_MUSCLE = 103
    CREATE_EXERCISE_EQUIPMENT = 104
