class BodyMetricStates:
    WAITING_WEIGHT = 1
    WAITING_BODY_FAT_PERCENT = 2
    WAITING_NECK = 3
    WAITING_CHEST = 4
    WAITING_WAIST = 5
    WAITING_HIPS = 6
    WAITING_THIGH = 7
    WAITING_CALF = 8
    WAITING_BICEPS = 9
    WAITING_NOTE = 10
