class BodyMetricStates:
    WAITING_VALUE = 1


class WorkoutStates:
    ENTER_SET_WEIGHT = 100
    ENTER_SET_REPS = 101
    SEARCH_EXERCISE = 102
    CREATE_EXERCISE_NAME = 103
    CREATE_EXERCISE_MUSCLE = 104
    CREATE_EXERCISE_EQUIPMENT = 105
