# Generated by Django 6.0.3 on 2026-03-24 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('primary_muscle', models.CharField(choices=[('chest', 'Грудь'), ('back', 'Спина'), ('shoulders', 'Плечи'), ('biceps', 'Бицепс'), ('triceps', 'Трицепс'), ('legs', 'Ноги (квадрицепс)'), ('glutes', 'Ягодицы'), ('calves', 'Икры'), ('core', 'Пресс/кор')], max_length=24)),
                ('secondary_muscle', models.CharField(blank=True, choices=[('chest', 'Грудь'), ('back', 'Спина'), ('shoulders', 'Плечи'), ('biceps', 'Бицепс'), ('triceps', 'Трицепс'), ('legs', 'Ноги (квадрицепс)'), ('glutes', 'Ягодицы'), ('calves', 'Икры'), ('core', 'Пресс/кор')], max_length=24, null=True)),
                ('equipment', models.CharField(choices=[('bodyweight', 'Собственный вес'), ('dumbbell', 'Гантели'), ('barbell', 'Штанга'), ('machine', 'Тренажёр'), ('kettlebell', 'Гиря'), ('cable', 'Блочный тренажёр'), ('other', 'Другое')], default='bodyweight', max_length=24)),
                ('is_basic', models.BooleanField(default=True)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TimeField(blank=True, null=True)),
                ('workout_type', models.CharField(choices=[('strength', 'Сила (низкие повторы, большой вес)'), ('hypertrophy', 'Масса (8–15 повторений)'), ('endurance', 'Выносливость (высокие повторения)'), ('power', 'Мощность (взрывные движения)'), ('full_body', 'Фуллбоди'), ('upper', 'Верх'), ('lower', 'Низ'), ('push', 'Жим (push)'), ('pull', 'Тяга (pull)'), ('cardio', 'Кардио'), ('mobility', 'Мобилити/растяжка'), ('deload', 'Делоад/лёгкая')], default='full_body', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_exercises', to='trainings.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trainings.workout')),
            ],
        ),
    ]
