# Generated by Django 6.0.3 on 2026-03-24 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set_number', models.PositiveIntegerField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('reps', models.PositiveIntegerField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Легко'), ('moderate', 'Средне'), ('hard', 'Тяжело')], default='moderate', max_length=20)),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='trainings.workoutexercise')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
