# Generated by Django 6.0.3 on 2026-04-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_alter_workout_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['set_number']},
        ),
        migrations.AddField(
            model_name='workout',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='set',
            unique_together={('workout_exercise', 'set_number')},
        ),
    ]
