# Generated by Django 6.0.3 on 2026-04-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_alter_set_options_workout_finished_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutexercise',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='workoutexercise',
            unique_together={('workout', 'order')},
        ),
    ]
